"""
https://www.practicepython.org

Exercise 18: Cows and Bulls
3 chilis

Create a program that will play the “cows and bulls” game with the user.
The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place, they
have a “cow”. For every digit the user guessed correctly in the wrong place
is a “bull.” Every time the user makes a guess, tell them how many “cows”
and “bulls” they have. Once the user guesses the correct number, the game
is over. Keep track of the number of guesses the user makes throughout teh
game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction
could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.

"""


import random

def generate_target():
    return(int(random.triangular() * 10000))

def compare(guess, target):
    if guess > 9999:
        print("guess must be 4 digits or less, try again.")
        return False

    cows = bulls = 0

    g = [ int((guess % 10000) / 1000),
          int((guess %  1000) /  100),
          int((guess %   100) /   10),
          int((guess %    10) /    1) ]

    t = [ int((target % 10000) / 1000),
          int((target %  1000) /  100),
          int((target %   100) /   10),
          int((target %    10) /    1) ]

    for i in 3, 2, 1, 0:
        if g[i] == t[i]:
            g.pop(i)
            t.pop(i)
            cows += 1

    for i in range(len(g)-1, -1, -1):
        if g[i] in t:
            t.pop(t.index(g[i]))
            g.pop(i)
            bulls += 1

    if cows == 4:
        return True
    else:
        print("cows: %d, bulls: %d " % (cows, bulls))
        return False

if __name__ == "__main__":
    target = generate_target()

    print("target is %4d" % target)
    
    guess_count = 1
    guess = int(input("What's your first guess? "))
    while False == compare(guess, target):
        guess_count += 1
        guess = int(input("What's your next guess? "))

    print("Took %d guesses to guess %4d." % (guess_count, target))

